# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
  	},
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
	
	# Uploading needed files to build a RPM package on VM
	box.vm.provision "file", source: "fifs.spec", destination: "~/fifs.spec"
#	box.vm.provision "file", source: "provision_rpm.sh", destination: "~/provision_rpm.sh"

 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              yum install -y rpmdevtools rpm-build
	SHELL

      end
  end
end

