# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "cdaf/CentOSLVM",
        :ip_addr => '192.168.11.101',
  	},
}


$bootstrap_VG = <<-SCRIPT
    OldVGname=centos_centoslvm
    NewVGname=OtusRoot
    
    echo 'Old VG name'
    
    vgs
    
    echo '\n\n\t\tRenaming VG'
    
    vgrename -v $OldVGname $NewVGname
    
    echo -e '\n\n\t\tDone!'
    
    vgs
    
    sed -i "s/$OldVGname/$NewVGname/g" /etc/fstab
    sed -i "s/$OldVGname/$NewVGname/g" /etc/default/grub
    sed -i "s/lv=$OldVGname/lv=$NewVGname/g" /boot/grub2/grub.cfg
    sed -i "s/$OldVGname-/$NewVGname-/g" /boot/grub2/grub.cfg
    
    mkinitrd -f -v /boot/initramfs-$(uname -r).img $(uname -r)
    
    echo "Please reboot OS and try to log in"

SCRIPT

$bootstrap_dracut = <<-SCRIPT

    mkdir -p /usr/lib/dracut/modules.d/01test
    curl -o /usr/lib/dracut/modules.d/01test/module-setup.sh https://gist.githubusercontent.com/lalbrekht/e51b2580b47bb5a150bd1a002f16ae85/raw/80060b7b300e193c187bbcda4d8fdf0e1c066af9/gistfile1.txt
    chmod 0755 /usr/lib/dracut/modules.d/01etst/module-setup.sh
    curl -o /usr/lib/dracut/modules.d/01test/test.sh https://gist.githubusercontent.com/lalbrekht/ac45d7a6c6856baea348e64fac43faf0/raw/69598efd5c603df310097b52019dc979e2cb342d/gistfile1.txt
    chmod 0755 /usr/lib/dracut/modules.d/test/test.sh
    mkinitrd -f -v /boot/initramfs-$(uname -r).img $(uname -r)
    dracut -f -v
    lsinitrd -m /boot/initramfs-$(uname -r).img | grep test
    sed -i "s/rghb quiet//g" /boot/grub2/grub.cfg
    echo "Please reboot OS"
    
SCRIPT

Vagrant.configure("2") do |config|


#config.vm.provider "virtualbox" do |vb|
#    vb.customize ["modifyvm", :id, "--usb", "off"]
#    vb.customize ["modifyvm", :id, "--usbehci", "off"]
#end



  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
	

     	  box.vm.provision "shell", inline: <<-SHELL
	          mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
          SHELL

# Провижн для переименования VG
#	  box.vm.provision "shell", inline: $bootstrap_VG

# Провижн для загрузки модуля через dracut
#	  box.vm.provision "shell", inline: $bootstrap_dracut

      end
  end
end

